# Generated by Django 5.2.17 on 2026-08-22 21:51

import django.db.models.deletion
import swamp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title; override for a custom URL.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown; rendered via django-markdownify wherever displayed.')),
                ('published', models.BooleanField(default=True, help_text='Unpublished works are hidden from the public site.')),
                ('featured', models.BooleanField(default=False, help_text='Featured works appear in the Home page teaser.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display order; lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=swamp.models.work_image_upload_to)),
                ('caption', models.TextField(blank=True, help_text='Markdown; rendered via django-markdownify wherever displayed.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display order within the gallery; order=1 is the thumbnail.')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='swamp.work')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
