# Generated by Django 5.2.17 on 2026-08-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title; override for a custom URL.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown; rendered via django-markdownify wherever displayed.')),
                ('icon', models.ImageField(blank=True, upload_to='resources/icons/')),
                ('file', models.FileField(upload_to='resources/files/')),
                ('published', models.BooleanField(default=True, help_text='Unpublished resources are hidden from the public site.')),
                ('featured', models.BooleanField(default=False, help_text='Featured resources appear in the Home page teaser.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display order; lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title; override for a custom URL.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown; rendered via django-markdownify wherever displayed.')),
                ('image', models.ImageField(blank=True, upload_to='training/')),
                ('published', models.BooleanField(default=True, help_text='Unpublished training entries are hidden from the public site.')),
                ('featured', models.BooleanField(default=False, help_text='Featured training entries appear in the Home page teaser.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display order; lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
