# Generated by Django 5.2.17 on 2026-09-21 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swamp', '0002_contactsubmission_resource_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG, PNG, JPG, or WebP.', upload_to='resources/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
